# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a9927f1dea83c75d21415fd5b1f72c0"
application_url = "https://best-selling-metafield-app-zf8f2.ondigitalocean.app"
embedded = true
name = "sort-by-best-selling"
handle = "sort-by-best-selling-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_metaobjects, write_metaobjects"

[auth]
redirect_urls = [
  "https://best-selling-metafield-app-zf8f2.ondigitalocean.app/auth/callback",
  "https://best-selling-metafield-app-zf8f2.ondigitalocean.app/auth/shopify/callback",
  "https://best-selling-metafield-app-zf8f2.ondigitalocean.app/api/auth/callback"
]

[pos]
embedded = false
