# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a9927f1dea83c75d21415fd5b1f72c0"
application_url = "https://example.com/"
embedded = true
name = "best-selling-metafield"
handle = "best-selling-metafield"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_metaobjects, read_products, read_metaobjects"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
