# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5bd88204c916538da187c761c573787b"
application_url = "https://07a5a58e03e9.ngrok-free.app"
embedded = true
name = "sort-by-best-selling"
handle = "sort-by-best-selling-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://07a5a58e03e9.ngrok-free.app/auth/callback",
  "https://07a5a58e03e9.ngrok-free.app/auth/shopify/callback",
  "https://07a5a58e03e9.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
